"""add code random_short_string

Revision ID: 3a27bd77b706
Revises: fffbd6b1370b
Create Date: 2019-12-26 10:33:17.902176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a27bd77b706'
down_revision = 'fffbd6b1370b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permission', 'permission_code',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('platform', 'platform_code',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('role', 'role_code',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'role_code',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    op.alter_column('platform', 'platform_code',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    op.alter_column('permission', 'permission_code',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    # ### end Alembic commands ###
