"""init db

Revision ID: 8da3ce17ab44
Revises: 
Create Date: 2019-12-31 14:15:36.870786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da3ce17ab44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_time', sa.BigInteger(), nullable=True),
    sa.Column('updated_time', sa.BigInteger(), nullable=True),
    sa.Column('platform_code', sa.String(length=40), nullable=False),
    sa.Column('permission_name', sa.String(length=40), nullable=False),
    sa.Column('permission_code', sa.String(length=40), nullable=True),
    sa.Column('permission_type', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Integer(), server_default='1', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_created_time'), 'permission', ['created_time'], unique=False)
    op.create_index(op.f('ix_permission_permission_code'), 'permission', ['permission_code'], unique=True)
    op.create_table('platform',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_time', sa.BigInteger(), nullable=True),
    sa.Column('updated_time', sa.BigInteger(), nullable=True),
    sa.Column('platform_name', sa.String(length=40), nullable=False),
    sa.Column('platform_code', sa.String(length=40), nullable=True),
    sa.Column('platform_host', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Integer(), server_default='1', nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_created_time'), 'platform', ['created_time'], unique=False)
    op.create_index(op.f('ix_platform_platform_code'), 'platform', ['platform_code'], unique=True)
    op.create_table('role',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_time', sa.BigInteger(), nullable=True),
    sa.Column('updated_time', sa.BigInteger(), nullable=True),
    sa.Column('platform_code', sa.String(length=40), nullable=False),
    sa.Column('role_name', sa.String(length=40), nullable=False),
    sa.Column('role_code', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_created_time'), 'role', ['created_time'], unique=False)
    op.create_index(op.f('ix_role_role_code'), 'role', ['role_code'], unique=True)
    op.create_table('role_permission',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_time', sa.BigInteger(), nullable=True),
    sa.Column('updated_time', sa.BigInteger(), nullable=True),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permission_created_time'), 'role_permission', ['created_time'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_time', sa.BigInteger(), nullable=True),
    sa.Column('updated_time', sa.BigInteger(), nullable=True),
    sa.Column('user_code', sa.String(length=40), nullable=False),
    sa.Column('platform_code', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created_time'), 'user', ['created_time'], unique=False)
    op.create_table('user_role',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_time', sa.BigInteger(), nullable=True),
    sa.Column('updated_time', sa.BigInteger(), nullable=True),
    sa.Column('user_code', sa.String(length=40), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Integer(), server_default='1', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role_created_time'), 'user_role', ['created_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_role_created_time'), table_name='user_role')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_user_created_time'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_permission_created_time'), table_name='role_permission')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_role_role_code'), table_name='role')
    op.drop_index(op.f('ix_role_created_time'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_platform_platform_code'), table_name='platform')
    op.drop_index(op.f('ix_platform_created_time'), table_name='platform')
    op.drop_table('platform')
    op.drop_index(op.f('ix_permission_permission_code'), table_name='permission')
    op.drop_index(op.f('ix_permission_created_time'), table_name='permission')
    op.drop_table('permission')
    # ### end Alembic commands ###
