"""add user model

Revision ID: d0c6730e635f
Revises: 3a27bd77b706
Create Date: 2019-12-26 15:10:40.852702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0c6730e635f'
down_revision = '3a27bd77b706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_time', sa.BigInteger(), nullable=True),
    sa.Column('updated_time', sa.BigInteger(), nullable=True),
    sa.Column('user_code', sa.String(length=40), nullable=False),
    sa.Column('platform_code', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created_time'), 'user', ['created_time'], unique=False)
    op.alter_column('user_role', 'role_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
    op.drop_column('user_role', 'platform_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_role', sa.Column('platform_code', mysql.VARCHAR(length=40), nullable=False))
    op.alter_column('user_role', 'role_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)
    op.drop_index(op.f('ix_user_created_time'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
